services:
  - type: web
    name: medical-ai-api
    env: python
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt

    startCommand: |
      gunicorn app:app --workers 1 --threads 2 --timeout 300

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"

      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"

      - key: KERAS_BACKEND
        value: "tensorflow"

    autoDeploy: true